import { games } from '/games/index.js?v=10';
const tg=window.Telegram?.WebApp||null;
try{tg?.ready?.();tg?.expand?.()}catch{}
const U=(()=>{try{return tg?.initDataUnsafe?.user||null}catch{return null}})();
const $=(s,r=document)=>r?.querySelector?.(s)||null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`${Math.max(0,Number(n||0)).toLocaleString('vi-VN')} Xu`;
const state={user:U,session:'',player:null,games:Array.isArray(games)?games.slice(0,75):[],petCatalog:[],shop:{},view:'home',muted:localStorage.getItem('casino-mute')==='1',audio:null,round:null,shown:18,search:'',lastView:''};
function toast(t){const e=$('#toast');if(!e)return;e.textContent=String(t);e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1400)}
function sfx(kind='click'){if(state.muted)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!state.audio)state.audio=new AC();const c=state.audio;if(c.state==='suspended')c.resume().catch(()=>{});if(c._last&&performance.now()-c._last<55)return;c._last=performance.now();const map={click:[380,.035],bet:[520,.045],win:[720,.07],lose:[150,.05],shop:[600,.04],bank:[300,.05]};const [f,d]=map[kind]||map.click;const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.03,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)}
function petBonus(){const p=state.petCatalog.find(x=>x.id===state.player?.activePet);return p?{xp:p.xpPct,money:p.moneyPct}:{xp:0,money:0}}
function header(){const p=state.player;if(!p)return;$('#name').textContent=p.name||'Người chơi';$('#balance').textContent=money(p.balance);$('#level').textContent=p.level||1;$('#vip').textContent=`VIP ${p.vip||0}`;const pb=petBonus();$('#petBonus').textContent=`Pet +${pb.money}% Xu · +${pb.xp}% XP`;const a=$('#avatar');if(a){a.replaceChildren();if(p.photo_url){const im=new Image();im.src=p.photo_url;im.width=46;im.height=46;im.alt='';im.loading='eager';im.onerror=()=>a.textContent='◆';a.appendChild(im)}else a.textContent='◆'}}
function setNav(){for(const b of $('#nav').children)b.classList.toggle('active',b.dataset.v===state.view)}
async function api(url,method='GET',body){const o={method,headers:{'Accept':'application/json'}};if(state.session)o.headers['X-App-Session']=state.session;if(method!=='GET'){o.headers['Content-Type']='application/json';o.body=JSON.stringify({...body,session:state.session})}const r=await fetch(url,o);const d=await r.json().catch(()=>({error:'Dữ liệu server không hợp lệ.'}));if(!r.ok)throw Error(d.error||'Yêu cầu thất bại.');return d}
function icon(m){return({dice:'🎲',wheel:'🎡',reels:'🎰',coin:'🪙',cards:'🃏',poker:'♠️',baccarat:'♦️',roulette:'🎯',plinko:'🔵',mines:'💎',crash:'🚀',keno:'🔢',baucua:'🦀',grid:'🟦'})[m]||'🎮'}
function card(g){return `<article class="game-card"><div class="gicon">${icon(g.mechanic)}</div><h3>${esc(g.name)}</h3><p>${esc(g.category||g.mechanic)}</p><button class="primary" data-game="${esc(g.id)}">Chơi</button></article>`}
function home(){const p=state.player;$('#view').innerHTML=`<section class="hero"><div class="eyebrow">SIÊU NHẸ</div><h1>CASINO SLOT VIETNAM</h1><p>Engine nhẹ cho Telegram WebView, không animation tự chạy, không canvas.</p><div class="stats"><div class="stat"><small>Số dư</small><strong>${money(p.balance)}</strong></div><div class="stat"><small>Level</small><strong>${p.level}</strong></div><div class="stat"><small>Tháng</small><strong>${p.monthlyStreak||0} ngày</strong></div></div></section><div class="section"><span>🔥 Nổi bật</span></div><div class="game-grid">${state.games.slice(0,8).map(card).join('')}</div><div class="section"><span>⚡ Hệ thống</span></div><div class="list"><div class="row"><span>XP</span><b>${p.xp}/${p.xpNeeded||1000}</b></div><div class="row"><span>Pet</span><b>${state.petCatalog.find(x=>x.id===p.activePet)?.name||'Chưa có'}</b></div></div>`}
function gamesView(){const q=state.search.toLocaleLowerCase('vi');const list=state.games.filter(g=>!q||g.name.toLocaleLowerCase('vi').includes(q));const vis=list.slice(0,state.shown);$('#view').innerHTML=`<div class="section"><span>🎮 75 GAME</span><small>Render ${vis.length}/${list.length}</small></div><div class="searchbar"><input id="search" class="input" value="${esc(state.search)}" placeholder="Tìm game…"></div><div id="gameGrid" class="game-grid">${vis.map(card).join('')}</div>${vis.length<list.length?'<button id="moreGames" class="secondary loadmore">Hiện thêm</button>':''}`}
function tasks(){const p=state.player;$('#view').innerHTML=`<div class="section"><span>📅 Đăng nhập tháng</span><small>${p.monthlyStreak||0} ngày</small></div><div class="hero"><p>Mỗi ngày đăng nhập nhận Xu. Các mốc 7/14/21/28/30/31 nhận thêm pet theo lịch tháng.</p><div class="list">${[1,7,14,21,28,30,31].map(d=>`<div class="row"><span>Ngày ${d}</span><b>${d<7?money(100*d):(d%7===0||d>=28?'🎁 Xu + Pet':'🪙 Xu')}</b></div>`).join('')}</div></div><div class="section"><span>🎁 Giftcode</span></div><div class="row"><input id="gift" class="input" placeholder="Nhập code"><button class="primary" id="redeem">Đổi</button></div>`}
async function rankings(){const d=await api('/api/rankings');const row=a=>`<div class="row"><span>#${a.rank} · ${esc(a.name)}</span><b>${money(a.balance??a.wins??a.xp)}</b></div>`;$('#view').innerHTML=`<div class="section"><span>🏆 TOP 100</span></div><div class="section"><span>💰 Giàu nhất</span></div><div class="list">${(d.richest||[]).slice(0,20).map(row).join('')}</div><div class="section"><span>⭐ XP</span></div><div class="list">${(d.xp||[]).slice(0,20).map(row).join('')}</div>`}
function profile(){const owned=Object.entries(state.player.pets||{}).map(([id,count])=>({pet:state.petCatalog.find(x=>x.id===id),count})).filter(x=>x.pet);$('#view').innerHTML=`<div class="section"><span>👤 Cá nhân</span></div><div class="hero"><b>${esc(state.player.name)}</b><p>Level ${state.player.level} · XP ${state.player.xp}/${state.player.xpNeeded||1000}</p><button class="secondary" id="rename">Đổi tên · 5.000 Xu</button></div><div class="section"><span>🐾 Pet đang sở hữu</span></div><div class="pet-grid">${owned.map(x=>`<div class="pet-card"><div class="pet-emoji">${x.pet.emoji}</div><b>${esc(x.pet.name)}</b><small>+${x.pet.xpPct}% XP · +${x.pet.moneyPct}% Xu · x${x.count}</small><button class="secondary" data-equip="${x.pet.id}">Trang bị</button><button class="danger" data-sell="${x.pet.id}">Bán 40%</button></div>`).join('')||'<div class="muted">Chưa có pet.</div>'}</div><div class="section"><span>🛒 Cửa hàng pet</span><small>80 pet</small></div><div class="pet-grid">${state.petCatalog.filter(x=>x.shop).slice(0,80).map(p=>`<div class="pet-card"><div class="pet-emoji">${p.emoji}</div><b>${esc(p.name)}</b><small>${money(p.price)} · +${p.xpPct}% XP · +${p.moneyPct}% Xu</small><button class="primary" data-buy="${p.id}">Mua</button></div>`).join('')}</div>`}
function bankView(b){$('#view').innerHTML=`<div class="section"><span>🏦 NGÂN HÀNG</span></div><section class="hero"><p>Lãi kép <b>10%/ngày</b>. Tiền phải khóa đủ <b>7 ngày</b> mới rút.</p><div class="stats"><div class="stat"><small>Đang gửi</small><strong>${money(b.principal)}</strong></div><div class="stat"><small>Ngày khóa</small><strong>${b.daysLocked}</strong></div><div class="stat"><small>Có thể rút</small><strong>${b.withdrawReady?'Có':'Chưa'}</strong></div></div><div class="actions"><input id="bankAmount" class="input" type="number" min="100" placeholder="Số Xu gửi"><button id="deposit" class="primary">Gửi</button></div><button id="withdraw" class="secondary" style="width:100%;margin-top:6px">Rút ${money(b.payout)}</button></section>`}
async function bank(){const d=await api('/api/bank');bankView(d.bank);}
function gameView(g,d){const m=g.mechanic;if(!d)return icon(m);if(m==='dice')return `<div class="dice-table">${(d.values||[]).map(v=>`<div class="die">${['','⚀','⚁','⚂','⚃','⚄','⚅'][v]||'⚄'}</div>`).join('')}</div>`;if(m==='wheel')return `<div class="wheel-wrap"><div class="pointer">▼</div><div class="wheel">${esc(d.value||'★')}</div></div>`;if(m==='reels')return `<div class="reels">${(d.values||[]).map(v=>`<div class="reel">${esc(v)}</div>`).join('')}</div>`;if(m==='coin')return `<div class="coin">${esc(d.value||'XU')}</div>`;return `<div class="visual-main">${icon(m)}</div>`}
function openGame(g){
  if(!g||state.round)return;
  const max=Math.min(1000000,Math.floor((state.player.balance||0)*0.75));
  if(max<100){toast('Cần ít nhất 100 Xu.');return;}
  const root=$('#modal-root');
  root.innerHTML=`<div class="modal-back"><section class="sheet"><div class="modal-head"><b>${esc(g.name)}</b><button class="close" id="closeGame">×</button></div><div class="stage"><div id="gameVisual" class="visual">${gameView(g,null)}</div><div id="gameMsg" class="result">Chọn cược</div><div class="bet-row">${[100,500,1000,5000,10000,50000,100000].filter(x=>x<=max).map(x=>`<button class="bet" data-bet="${x}">${money(x)}</button>`).join('')}</div><input id="betInput" class="input" type="number" min="100" max="${max}" step="100" value="${Math.min(1000,max)}"><div class="actions"><button id="playGame" class="primary">BẮT ĐẦU</button></div></div></section></div>`;
  $('#closeGame',root).onclick=()=>root.replaceChildren();
  root.onclick=e=>{const b=e.target.closest('[data-bet]');if(b){const input=$('#betInput',root);if(input)input.value=b.dataset.bet;sfx('bet')}};
  $('#playGame',root).onclick=()=>play(g,root);
}

async function play(g,root){
  if(state.round)return;
  const betInput=$('#betInput',root); const playBtn=$('#playGame',root); const visual=$('#gameVisual',root); const msg=$('#gameMsg',root);
  if(!betInput||!playBtn||!visual||!msg)return;
  const bet=Math.floor(Number(betInput.value));
  const max=Math.min(1000000,Math.floor(state.player.balance*.75));
  if(!Number.isSafeInteger(bet)||bet<100||bet>max){toast('Mức cược không hợp lệ.');return;}
  state.round={game:g}; playBtn.disabled=true; msg.className='result'; msg.textContent='Đang xử lý…'; sfx('click');
  try{
    const requestId=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
    const data=await api('/api/play','POST',{gameId:g.id,bet,requestId});
    state.player=data.player; header(); visual.innerHTML=gameView(g,data.result.display);
    msg.className='result '+(data.result.win?'win':'lose');
    msg.textContent=data.result.win?`🎉 THẮNG x${data.result.multiplier} · +${money(Math.floor(bet*data.result.multiplier))}`:'😵 Chưa trúng lượt này';
    if(data.result.win)sfx('win');
  }catch(e){msg.className='result lose';msg.textContent=e.message||'Không thể chơi.';}
  finally{playBtn.disabled=false;state.round=null;}
}

async function boot(){try{const d=await api('/api/bootstrap','POST',{initData:tg?.initData||'',telegramUser:state.user||undefined});if(!d?.player?.id)throw Error('Máy chủ không trả Telegram ID.');state.session=d.session;state.player=d.player;state.games=Array.isArray(games)?games.slice(0,75):[];state.petCatalog=Array.isArray(d.pets)?d.pets:[];state.shop=d.shop||{};header();render();if(d.loginReward)toast(`🎁 ${money(d.loginReward.xu)}${d.loginReward.pet?' · +1 pet':''}`);if(state.player.needsName)nameModal()}catch(e){const v=$('#view');if(v)v.innerHTML=`<section class="hero"><h1>Không thể mở Mini App</h1><p>${esc(e.message)}</p></section>`;toast(e.message)}}
function nameModal(){const root=$('#modal-root');root.innerHTML=`<div class="modal-back"><section class="sheet"><h2>Đặt tên</h2><p>Lần đầu miễn phí. Đổi tên sau tốn 5.000 Xu.</p><input id="firstName" class="input" maxlength="40" placeholder="Tên hiển thị"><button id="saveName" class="primary" style="margin-top:6px">Vào game</button></section></div>`;$('#saveName').onclick=async()=>{const name=$('#firstName').value.trim();if(name.length<2)return toast('Tên cần ít nhất 2 ký tự.');try{const d=await api('/api/profile/name','POST',{name,first:true});state.player=d.player;root.replaceChildren();header();render()}catch(e){toast(e.message)}}}
const navEl=$('#nav'); if(navEl) navEl.addEventListener('click',e=>{const b=e.target.closest('[data-v]');if(!b)return;state.view=b.dataset.v;sfx('click');if(state.view==='rank')rankings().catch(x=>toast(x.message));else if(state.view==='bank')bank().catch(x=>toast(x.message));else render()});
const viewEl=$('#view'); if(viewEl) viewEl.addEventListener('click',async e=>{const g=e.target.closest('[data-game]');if(g){openGame(state.games.find(x=>x.id===g.dataset.game));return}if(e.target.id==='moreGames'){state.shown+=18;gamesView();return}const buy=e.target.closest('[data-buy]');if(buy){try{const d=await api('/api/pets/buy','POST',{petId:buy.dataset.buy});state.player=d.player;header();sfx('shop');profile()}catch(x){toast(x.message)}return}const eq=e.target.closest('[data-equip]');if(eq){try{const d=await api('/api/pets/equip','POST',{petId:eq.dataset.equip});state.player=d.player;header();profile()}catch(x){toast(x.message)}return}const sell=e.target.closest('[data-sell]');if(sell){try{const d=await api('/api/pets/sell','POST',{petId:sell.dataset.sell});state.player=d.player;header();profile()}catch(x){toast(x.message)}return}if(e.target.id==='redeem'){try{const d=await api('/api/giftcode/redeem','POST',{code:$('#gift').value});state.player=d.player;header();toast('🎁 Đã nhận quà')}catch(x){toast(x.message)}}if(e.target.id==='rename'){const n=prompt('Tên mới:');if(n){try{const d=await api('/api/profile/name','POST',{name:n,first:false});state.player=d.player;header();profile()}catch(x){toast(x.message)}}}if(e.target.id==='deposit'){try{const d=await api('/api/bank/deposit','POST',{amount:Math.floor(Number($('#bankAmount').value))});state.player=d.player;header();sfx('bank');bankView({...d.bank,daysLocked:0,payout:d.bank.principal,withdrawReady:false})}catch(x){toast(x.message)}}if(e.target.id==='withdraw'){try{const d=await api('/api/bank/withdraw','POST',{});state.player=d.player;header();sfx('bank');toast(`Đã rút ${money(d.payout)}`);bank()}catch(x){toast(x.message)}}});
if(viewEl) viewEl.addEventListener('input',e=>{if(e.target.id==='search'){state.search=e.target.value;state.shown=18;clearTimeout(state.searchTimer);state.searchTimer=setTimeout(gamesView,90)}});
const themeEl=$('#theme'); if(themeEl) themeEl.onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('casino-theme',document.documentElement.classList.contains('dark')?'dark':'light')};const audioEl=$('#audio'); if(audioEl) audioEl.onclick=()=>{state.muted=!state.muted;localStorage.setItem('casino-mute',state.muted?'1':'0');$('#audio').textContent=state.muted?'🔇':'🔊';if(!state.muted)sfx('click')};if(localStorage.getItem('casino-theme')==='dark')document.documentElement.classList.add('dark');if(audioEl) audioEl.textContent=state.muted?'🔇':'🔊';
function render(){setNav();if(state.view==='home')home();else if(state.view==='games')gamesView();else if(state.view==='tasks')tasks();else if(state.view==='profile')profile();else if(state.view==='bank')bank().catch(x=>toast(x.message));else if(state.view==='rank')rankings().catch(x=>toast(x.message));}
boot();
