import { games } from '/games/index.js';

const tg = (()=>{try{return window.Telegram?.WebApp||null}catch{return null}})();
try{tg?.ready?.();tg?.expand?.()}catch{}

function readTelegramUser(){try{const u=tg?.initDataUnsafe?.user;return u&&typeof u==='object'?u:{}}catch{return {}}}
function readInitData(){try{return typeof tg?.initData==='string'?tg.initData:''}catch{return ''}}
const safeUser=readTelegramUser();
const state={user:safeUser,id:safeUser?.id?String(safeUser.id):'',session:'',player:null,view:'home',stream:null,current:null,mute:localStorage.getItem('casino-mute')==='1'};
const $=(s,r=document)=>r?.querySelector?.(s)||null; const $$=(s,r=document)=>r?[...r.querySelectorAll(s)]:[];
const money=n=>`${Math.max(0,Number(n||0)).toLocaleString('vi-VN')} Xu`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const icons={dice:'🎲',wheel:'🎡',baucua:'🦀',coin:'🪙',reels:'🎰',cards:'🃏',poker:'🂡',baccarat:'♦️',roulette:'🎯',plinko:'🔵',mines:'💎',crash:'🚀',keno:'🎱',pick:'🎁',grid:'💠'};
function toast(t){const e=$('#toast');if(!e)return;e.textContent=String(t);e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),2100)}
function setText(sel,v){const e=$(sel);if(e)e.textContent=String(v??'')}
function header(){const p=state.player;if(!p)return;setText('#name',p.name||'Người chơi');setText('#balance',money(p.balance));setText('#level',p.level||1);setText('#vip',`VIP ${p.vip||0}`);const a=$('#avatar');if(a){a.textContent='🎰';if(p.photo_url){const img=document.createElement('img');img.src=p.photo_url;img.alt='';img.referrerPolicy='no-referrer';img.onerror=()=>{a.textContent='🎰'};a.replaceChildren(img)}}}
function nav(){ $$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===state.view)) }

function sfx(mech,type='click'){
  if(state.mute)return;
  try{
    const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;
    const c=sfx.ctx||(sfx.ctx=new AC());if(c.state==='suspended')c.resume();
    const base={dice:170,wheel:250,coin:420,reels:120,cards:300,poker:330,baccarat:290,roulette:230,plinko:390,mines:140,crash:180,keno:320,pick:360,grid:220}[mech]||260;
    const now=c.currentTime,o=c.createOscillator(),g=c.createGain();
    o.type=type==='win'?'triangle':'sine';o.frequency.setValueAtTime(type==='win'?base*1.2:base,now);o.frequency.exponentialRampToValueAtTime(Math.max(70,type==='win'?base*1.8:base*.72),now+.18);g.gain.setValueAtTime(type==='win'?.05:.022,now);g.gain.exponentialRampToValueAtTime(.001,now+.2);o.connect(g).connect(c.destination);o.start(now);o.stop(now+.21);
  }catch{}
}

function card(g){return `<article class="card"><div class="ico">${icons[g.mechanic]||'🎮'}</div><h3>${esc(g.name)}</h3><div class="game-meta">${esc(g.category)} · ${esc(g.mechanic)}</div><button class="secondary" data-game="${esc(g.id)}">Chơi ngay</button></article>`}
function home(){const p=state.player;$('#view').innerHTML=`<section class="hero"><div class="eyebrow">SẢNH CAO CẤP · MÁY YẾU CŨNG CHẠY</div><h2>ĐIỆN ẢNH, NHƯNG NHẸ.</h2><p>${games.length} trò chơi, xử lý cược tại server, animation CSS tối giản và SFX Web Audio không cần tải file âm thanh nặng.</p><div class="stats"><div class="stat"><small>Số dư</small><strong>${money(p.balance)}</strong></div><div class="stat"><small>Chuỗi đăng nhập</small><strong>${p.currentStreak} ngày</strong></div><div class="stat"><small>Đã chơi</small><strong>${p.totalPlays}</strong></div></div></section><div class="section"><span>🔥 Nổi bật</span><small>${games.length} game</small></div><div class="grid">${games.slice(0,12).map(card).join('')}</div><div class="section"><span>⚡ Hệ thống</span></div><div class="list"><div class="row"><span>🎟️ Free Spin</span><b>${p.freeSpins}</b></div><div class="row"><span>⭐ VIP / XP</span><b>VIP ${p.vip} · ${p.xp}/1000 XP</b></div><div class="row"><span>🐾 Pet</span><b>${Object.keys(p.pets||{}).length}</b></div><div class="row"><span>🏆 Thành tựu</span><b>650+</b></div></div>`;bindGameCards()}
function gamesView(){ $('#view').innerHTML=`<div class="section"><span>🎮 KHO GAME</span><small>Chạm để chơi</small></div><div class="search-row"><input id="search" class="filter" placeholder="Tìm tên game hoặc thể loại…"><button class="secondary" id="all">Tất cả</button></div><div class="game-tabs" id="filters" style="margin-top:8px"><button class="active" data-f="all">Tất cả</button><button data-f="dice">Xúc xắc</button><button data-f="wheel">Vòng quay</button><button data-f="reels">Slot</button><button data-f="cards">Bài</button><button data-f="grid">Ô</button><button data-f="crash">Hệ số</button></div><div id="game-grid" class="grid" style="margin-top:9px">${games.map(card).join('')}</div>`;bindGameCards();let filter='all';const paint=()=>{const q=($('#search')?.value||'').toLowerCase();const arr=games.filter(g=>(filter==='all'||g.mechanic===filter)&&(`${g.name} ${g.category}`.toLowerCase().includes(q)));const el=$('#game-grid');if(el){el.innerHTML=arr.map(card).join('');bindGameCards()}};$('#search').oninput=paint;$('#all').onclick=()=>{$('#search').value='';filter='all';$$('#filters button').forEach(b=>b.classList.toggle('active',b.dataset.f==='all'));paint()};$$('#filters button').forEach(b=>b.onclick=()=>{filter=b.dataset.f;$$('#filters button').forEach(x=>x.classList.toggle('active',x===b));paint()})}
function bindGameCards(){$$('[data-game]').forEach(b=>b.onclick=()=>openGame(b.dataset.game))}
function tasks(){const p=state.player;$('#view').innerHTML=`<div class="section"><span>✦ NHIỆM VỤ</span><small>Thưởng mỗi ngày</small></div><div class="list"><div class="task"><span>Chơi 10 ván bất kỳ</span><b>${Math.min(10,p.totalPlays)}/10</b></div><div class="task"><span>Thắng 5 ván</span><b>${Math.min(5,p.totalWins)}/5</b></div><div class="task"><span>Đăng nhập hôm nay</span><b>✓</b></div><div class="task"><span>🎡 Free Spin</span><button class="secondary" id="free-spin" style="width:auto;margin:0">Quay</button></div><div class="task" style="align-items:stretch;flex-direction:column"><span>🎁 Giftcode</span><div class="search-row" style="width:100%"><input id="gift" class="filter" placeholder="Nhập giftcode"><button id="redeem" class="primary" style="width:auto;margin:0">Đổi</button></div></div></div><div class="section"><span>🏆 Thành tựu</span><small>650+</small></div><div class="hero"><p>Tiến độ được cập nhật phía server theo hoạt động của bạn.</p><div class="bar-wrap" style="margin-top:10px"><div class="bar" style="width:${Math.min(100,p.totalWins)}%"></div></div></div>`;$('#redeem').onclick=redeemGift;$('#free-spin').onclick=freeSpin}
async function redeemGift(){const code=$('#gift')?.value?.trim();if(!code)return toast('Nhập giftcode.');const d=await api('/api/giftcode/redeem','POST',{code});if(d){state.player=d.player;header();const giftInput=$('#gift');if(giftInput)giftInput.value='';toast(`🎁 Đã nhận ${money(d.reward||0)}${d.pet?` · Pet ${d.pet}`:''}`)}}
async function freeSpin(){const d=await api('/api/free-spin','POST',{});if(d){state.player=d.player;header();toast(`🎡 +${money(d.reward)}`)}}
async function rank(){ $('#view').innerHTML=`<div class="section"><span>♛ XẾP HẠNG</span><small>Top 100</small></div><div class="rank-tabs"><button class="secondary" data-r="richest" style="width:auto;margin:0">Giàu nhất</button><button class="secondary" data-r="streak" style="width:auto;margin:0">Chuỗi</button><button class="secondary" data-r="weekly" style="width:auto;margin:0">Thắng tuần</button></div><div id="rankList" class="list" style="margin-top:9px">Đang tải…</div><div class="section"><span>💬 CHAT ROOM</span><small>Realtime</small></div><div id="chat" class="list" style="max-height:230px;overflow:auto"></div><div class="search-row" style="margin-top:7px"><input id="chatInput" class="filter" maxlength="300" placeholder="Nhập tin nhắn…"><button id="chatSend" class="primary" style="width:auto;margin:0">Gửi</button></div>`;$$('[data-r]').forEach(b=>b.onclick=()=>loadRank(b.dataset.r));loadRank('richest');startChat()}
async function loadRank(k){const d=await api('/api/rankings','GET');const a=d?.[k]||[],el=$('#rankList');if(!el)return;el.innerHTML=a.map(x=>`<div class="row"><span>#${x.rank} · ${esc(x.name)}</span><b>${k==='richest'?money(x.balance):k==='streak'?`${x.streak} ngày`:`${x.wins} thắng`}</b></div>`).join('')||'<div class="muted">Chưa có dữ liệu.</div>'}
function chatRow(x){return `<div class="row"><span><b>${esc(x?.name||'Người chơi')}</b><br><span class="muted">${esc(x?.text||'')}</span></span><span class="mini">${x?.time?new Date(x.time).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'}):''}</span></div>`}
function startChat(){const box=$('#chat');if(!box)return;if(state.stream)state.stream.close();state.stream=new EventSource('/api/events');state.stream.addEventListener('chat_history',e=>{try{const a=JSON.parse(e.data||'[]');box.innerHTML=a.map(chatRow).join('')||'<div class="muted">Chưa có tin nhắn.</div>'}catch{}});state.stream.addEventListener('chat_message',e=>{try{box.insertAdjacentHTML('beforeend',chatRow(JSON.parse(e.data||'{}')));box.scrollTop=box.scrollHeight}catch{}});$('#chatSend').onclick=async()=>{const text=$('#chatInput').value.trim();if(!text)return;const d=await api('/api/chat','POST',{text});if(d)$('#chatInput').value=''}}
async function profile(){const [h,shop]=await Promise.all([api('/api/history?id='+encodeURIComponent(state.id),'GET'),api('/api/shop','GET')]);const p=state.player;$('#view').innerHTML=`<div class="section"><span>◉ CÁ NHÂN</span><small>${esc(state.id||'Telegram')}</small></div><div class="stats"><div class="stat"><small>Tổng ván</small><strong>${p.totalPlays}</strong></div><div class="stat"><small>Tổng thắng</small><strong>${p.totalWins}</strong></div><div class="stat"><small>Best streak</small><strong>${p.bestStreak}</strong></div></div><div class="section"><span>🛍️ CỬA HÀNG</span><small>Mua bằng Xu</small></div><div id="shop" class="grid"></div><div class="section"><span>🐾 PET</span></div><div class="grid">${Object.entries(p.pets||{}).map(([id,n])=>`<div class="card"><div class="ico">🐾</div><h3>${esc(id)}</h3><div class="game-meta">Số lượng ${n}</div></div>`).join('')||'<div class="muted">Chưa có pet.</div>'}</div><div class="section"><span>📜 LỊCH SỬ</span><small>80 gần nhất</small></div><div class="list">${(h||[]).map(x=>`<div class="row"><span>${esc(x?.gameName||x?.gameId)} · ${money(x?.bet)}</span><b class="${x?.result==='win'?'win':'lose'}">${x?.result==='win'?`THẮNG x${x.multiplier}`:'THUA'}</b></div>`).join('')||'<div class="muted">Chưa có lịch sử.</div>'}</div>`;const sh=$('#shop');if(sh)sh.innerHTML=Object.entries(shop||{}).map(([id,it])=>`<div class="card"><div class="ico">🛍️</div><h3>${esc(it.name)}</h3><div class="game-meta">${money(it.price)}</div><button class="secondary" data-shop="${esc(id)}">Mua</button></div>`).join('');$$('[data-shop]').forEach(b=>b.onclick=async()=>{const d=await api('/api/shop/buy','POST',{item:b.dataset.shop});if(d){state.player=d.player;header();toast('✅ Đã mua '+d.item.name)}})}
function visual(g,mode,d){const m=g.mechanic;if(mode==='idle')return `<div><div class="big">${icons[m]||'🎮'}</div><div class="idle-label">${esc(g.name)} · chọn cược rồi bắt đầu</div></div>`;if(mode==='play'){if(m==='reels')return `<div class="reels spinning"><div class="reel">🍒</div><div class="reel">💎</div><div class="reel">7️⃣</div></div>`;if(m==='dice')return `<div class="dice rolling"><div class="die">⚄</div><div class="die">⚁</div><div class="die">⚅</div></div>`;if(m==='wheel')return `<div class="wheel spinning">XOAY</div>`;if(m==='coin')return `<div class="coin flipping">XU</div>`;if(['cards','poker','baccarat'].includes(m))return `<div class="cards"><div class="playing-card">🂠</div><div class="playing-card">🂠</div><div class="playing-card">🂠</div></div>`;if(['grid','mines'].includes(m))return `<div class="grid-board">${Array.from({length:25},(_,i)=>`<button class="grid-cell" disabled>${i+1}</button>`).join('')}</div>`;if(['keno','plinko'].includes(m))return `<div class="keno">${[1,7,13,21,32,38,44].map(x=>`<div class="ball">${x}</div>`).join('')}</div>`;return `<div><div class="big">${icons[m]||'✨'}</div><div class="crash-meter">ĐANG XỬ LÝ</div></div>`}const x=d||{};if(m==='reels')return `<div class="reels"><div class="reel">${esc(x.values?.[0]||'🍒')}</div><div class="reel">${esc(x.values?.[1]||'💎')}</div><div class="reel">${esc(x.values?.[2]||'7️⃣')}</div></div>`;if(m==='dice'){const f=['','⚀','⚁','⚂','⚃','⚄','⚅'];return `<div><div class="dice">${(x.values||[5,3,6]).map(v=>`<div class="die">${f[v]||'⚄'}</div>`).join('')}</div><div style="margin-top:7px">Tổng: <b>${x.sum??''}</b></div></div>`}if(m==='wheel')return `<div class="wheel">${esc(x.value||'★')}</div>`;if(m==='coin')return `<div class="coin">${esc(x.value||'MẶT NGỬA')}</div>`;if(['cards','poker','baccarat'].includes(m))return `<div class="cards">${(x.values||['A♠','10♥','7♦']).map(v=>`<div class="playing-card">${esc(v)}</div>`).join('')}</div>`;if(['keno','plinko'].includes(m))return `<div class="keno">${(x.values||[3,8,17,22,31,40]).map(v=>`<div class="ball">${esc(v)}</div>`).join('')}</div>`;if(['grid','mines'].includes(m))return `<div class="grid-board">${(x.values||Array.from({length:25},(_,i)=>i+1)).map(v=>`<div class="grid-cell revealed">${esc(v)}</div>`).join('')}</div>`;return `<div><div class="big">${icons[m]||'🎯'}</div><div class="crash-meter">${esc(x.headline||'KẾT QUẢ')}</div></div>`}
function choiceUI(g){if(g.id==='tai-xiu'||g.id==='sum-guess')return `<div class="quick-choice"><button data-choice="tai">Tài</button><button data-choice="xiu">Xỉu</button></div>`;if(g.mechanic==='coin')return `<div class="quick-choice"><button data-choice="ngửa">Ngửa</button><button data-choice="sấp">Sấp</button></div>`;if(g.mechanic==='cards')return `<div class="quick-choice"><button data-choice="cao">Cao</button><button data-choice="thap">Thấp</button></div>`;if(g.mechanic==='pick')return `<div class="quick-choice"><button data-choice="1">Lựa chọn 1</button><button data-choice="2">Lựa chọn 2</button><button data-choice="3">Lựa chọn 3</button></div>`;return ''}
async function openGame(id){const g=games.find(x=>x?.id===id);if(!g||!state.player)return toast('Không tìm thấy game hoặc phiên chơi.');const max=Math.min(1000000,Math.floor(Number(state.player.balance||0)*.2));if(max<100)return toast('Cần ít nhất 100 Xu để chơi.');const root=$('#modal-root');if(!root)return;root.innerHTML=`<div class="modal-back"><section class="sheet"><div class="modal-head"><div><div class="game-title">${esc(g.name)}</div><div class="game-meta">${esc(g.category)} · Xu ảo · server settlement</div></div><button class="close" aria-label="Đóng">×</button></div><div class="stage"><div class="stage-top"><span>Tối thiểu 100 Xu</span><span>Tối đa ${money(max)}</span></div><div id="visual" class="visual">${visual(g,'idle')}</div><div class="progress-line"><div id="roundProgress" class="progress-fill"></div></div><div id="result" class="result">Chọn cược rồi bắt đầu</div>${choiceUI(g)}<div class="bets">${[100,500,1000,5000,10000,50000].filter(x=>x<=max).map(x=>`<button class="bet" data-b="${x}">${money(x)}</button>`).join('')}</div><input id="bet" class="bet-input" type="number" min="100" max="${max}" value="${Math.min(1000,max)}" step="100"><div class="actions" style="grid-template-columns:1fr 1fr"><button id="play" class="primary">BẮT ĐẦU VÁN</button><button id="skip" class="secondary" disabled>Hiện kết quả</button></div><div class="mini" style="margin-top:8px">Bản tối ưu máy yếu: không hạt đồ họa, không canvas, không animation loop dài. SFX được tạo tại máy và tự tắt khi bật chế độ im lặng.</div></div></section></div>`;root.querySelector('.close').onclick=()=>{root.replaceChildren()};$$('[data-b]',root).forEach(b=>b.onclick=()=>{const inp=$('#bet',root);if(inp)inp.value=b.dataset.b;$$('.bet',root).forEach(x=>x.classList.toggle('selected',x===b));sfx(g.mechanic)});$$('[data-choice]',root).forEach(b=>b.onclick=()=>{$$('[data-choice]',root).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');sfx(g.mechanic)});$('#play',root).onclick=()=>startRound(root.querySelector('.modal-back'),g)}
async function startRound(modal,g){if(!modal||modal.dataset.playing==='1')return;const bet=Math.floor(Number($('#bet',modal)?.value));const max=Math.min(1000000,Math.floor(Number(state.player.balance||0)*.2));if(!Number.isSafeInteger(bet)||bet<100||bet>max)return toast(`Cược hợp lệ: 100–${money(max)}`);const play=$('#play',modal),skip=$('#skip',modal),bar=$('#roundProgress',modal),vis=$('#visual',modal),result=$('#result',modal);if(!play||!skip||!bar||!vis||!result)return toast('Giao diện game chưa sẵn sàng.');modal.dataset.playing='1';play.disabled=true;skip.disabled=true;sfx(g.mechanic);vis.innerHTML=visual(g,'play');bar.style.animationPlayState='running';const rid=window.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`;const choice=$('[data-choice].selected',modal)?.dataset.choice||'';let data=null,done=false,finishTimer=null,skipTimer=null;const finish=()=>{if(done)return;done=true;clearTimeout(finishTimer);clearTimeout(skipTimer);bar.style.animationPlayState='paused';skip.disabled=true;if(!data){play.disabled=false;modal.dataset.playing='0';return toast('Máy chủ chưa trả kết quả. Hãy thử lại.')}state.player=data.player;header();vis.innerHTML=visual(g,'done',data.result?.display||{});const win=!!data.result?.win;result.className='result '+(win?'win':'lose');result.textContent=win?`🎉 THẮNG · x${data.result.multiplier} · +${money(Math.floor(bet*data.result.multiplier))}`:'😵 Chưa trúng lượt này';sfx(g.mechanic,win?'win':'lose');play.disabled=false;play.textContent='CHƠI LẠI';modal.dataset.playing='0'};skipTimer=setTimeout(()=>{if(!done)skip.disabled=false},900);skip.onclick=finish;finishTimer=setTimeout(finish,20000);try{const ctrl=new AbortController();const timeout=setTimeout(()=>ctrl.abort(),10000);const r=await fetch('/api/play',{method:'POST',headers:{'Content-Type':'application/json','X-App-Session':state.session},body:JSON.stringify({gameId:g.id,bet,choice,requestId:rid,session:state.session}),signal:ctrl.signal});clearTimeout(timeout);data=await r.json().catch(()=>null);if(!r.ok||!data)throw Error(data?.error||'Không thể xử lý lượt chơi');if(!done)bar.style.animationDuration=`${Math.max(4,Math.round(Number(data.result?.durationMs||20000)/1000))}s`}catch(e){clearTimeout(finishTimer);clearTimeout(skipTimer);bar.style.animationPlayState='paused';result.className='result lose';result.textContent=e?.name==='AbortError'?'Máy chủ phản hồi chậm. Hãy thử lại.':(e?.message||'Không thể kết nối máy chủ.');play.disabled=false;skip.disabled=true;modal.dataset.playing='0'}}
async function api(url,method='GET',body={}){try{const headers={'Content-Type':'application/json'};if(state.session)headers['X-App-Session']=state.session;const opt={method,headers};if(method!=='GET')opt.body=JSON.stringify({...body,session:state.session});const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok){toast(d.error||'Có lỗi máy chủ');return null}return d}catch(e){toast(e?.message||'Không kết nối được máy chủ');return null}}
function connectEvents(){if(state.stream)state.stream.close();state.stream=new EventSource('/api/events');state.stream.addEventListener('big_win',e=>{try{const x=JSON.parse(e.data);const t=$('#tickerText');if(t)t.textContent=`🎉 ${x.name} vừa thắng tại ${x.game}`;}catch{}});state.stream.addEventListener('system_notice',e=>{try{const x=JSON.parse(e.data);const t=$('#tickerText');if(t)t.textContent=x.text||'Có thông báo mới';}catch{}})}
async function bootstrap(){try{const tgData=readInitData();const body={initData:tgData};if(safeUser?.id)body.telegramUser=safeUser;const r=await fetch('/api/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Không thể tạo phiên Mini App.');state.session=d.session||'';state.player=d.player||null;if(!state.player)throw Error('Máy chủ không trả hồ sơ người chơi.');state.id=String(state.player.id||safeUser?.id||'');header();if(d.loginReward)toast(`🎁 +${money(d.loginReward.xu)} · ${d.loginReward.spins||0} lượt quay`);connectEvents();render()}catch(e){const v=$('#view');if(v)v.innerHTML=`<section class="hero"><div class="eyebrow">TELEGRAM MINI APP</div><h2>KHÔNG THỂ KHỞI TẠO.</h2><p>${esc(e?.message||'Lỗi không xác định.')}</p><p class="muted">Đóng Mini App, quay lại bot và bấm MỞ CASINO. Nếu bạn đã cập nhật code trên Render, hãy chờ deploy hoàn tất rồi mở lại.</p></section>`;toast(e?.message||'Không thể khởi tạo.')}}
function render(){nav();if(state.view==='home')home();else if(state.view==='games')gamesView();else if(state.view==='tasks')tasks();else if(state.view==='rank')rank();else profile()}
$('#nav')?.addEventListener('click',e=>{const b=e.target?.closest?.('button[data-v]');if(!b)return;state.view=b.dataset.v;render()});$('#theme')?.addEventListener('click',()=>{const light=document.documentElement.classList.toggle('light');localStorage.setItem('casino-theme',light?'light':'dark');setText('#theme',light?'☀':'☾')});if(localStorage.getItem('casino-theme')==='light')document.documentElement.classList.add('light');setText('#theme',document.documentElement.classList.contains('light')?'☀':'☾');$('#audio')?.addEventListener('click',()=>{state.mute=!state.mute;localStorage.setItem('casino-mute',state.mute?'1':'0');setText('#audio',state.mute?'🔇':'🔊');if(!state.mute)sfx('coin')});
bootstrap();
