const fs=require('fs'),path=require('path');
const root=__dirname;
const checks=[];
function ok(name,cond,detail=''){checks.push({name,ok:!!cond,detail});}
const games=JSON.parse(fs.readFileSync(path.join(root,'server','games.json'),'utf8'));
const pets=JSON.parse(fs.readFileSync(path.join(root,'server','pets.json'),'utf8'));
const features=JSON.parse(fs.readFileSync(path.join(root,'server','featureCatalog.json'),'utf8'));
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'styles.css'),'utf8');
const server=fs.readFileSync(path.join(root,'server','server.js'),'utf8');
ok('75 active games',games.length===75,String(games.length));
ok('unique game ids',new Set(games.map(x=>x.id)).size===75);
ok('100 pets',pets.length>=100,String(pets.length));
ok('unique pet ids',new Set(pets.map(x=>x.id)).size===pets.length);
ok('10000 feature catalog',features.length===10000,String(features.length));
ok('state games initialized',app.includes('games:Array.isArray(GAME_DEFS)?GAME_DEFS:[]'));
ok('game endpoint',server.includes("app.post('/api/play'"));
ok('cooldown',server.includes('COOLDOWN_MS=3000')&&server.includes('now-last<COOLDOWN_MS'));
ok('75% max bet',server.includes('.75'));
ok('42% scheduler',server.includes('.42'));
ok('web session endpoint',server.includes("app.get('/api/session'"));
ok('web boot session path',app.includes("api('/api/session')"));
ok('bank 10%',server.includes('Math.pow(1.10,full)'));
ok('7 day lock',server.includes('7*86400000'));
ok('admin petsid',server.includes("cmd==='/petsid'"));
ok('admin taopet',server.includes("cmd==='/taopet'"));
ok('admin baotri',server.includes("cmd==='/baotri'"));
ok('admin ban',server.includes("cmd==='/ban'"));
ok('start webhook',server.includes("cmd==='/start'")&&server.includes("method:'sendMessage'"));
ok('ownerhelp',server.includes("cmd==='/ownerhelp'"));
ok('no canvas',!app.includes('canvas')&&!css.includes('canvas'));
ok('no raf',!app.includes('requestAnimationFrame'));
if(checks.some(x=>!x.ok)){console.error(JSON.stringify(checks,null,2));process.exit(1)}
console.log(JSON.stringify(checks,null,2));
