const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');
const r=__dirname; const req=['index.html','styles.css','app.js','package.json','render.yaml','README.md','FEATURES_1000.md','server/server.js','server/games.json','server/pets.json','server/achievements.json','server/featureCatalog.json','server/database/db.json','games/index.js'];
for(const f of req)if(!fs.existsSync(path.join(r,f)))throw Error('missing '+f);
for(const f of fs.readdirSync(path.join(r,'games')).filter(x=>x.endsWith('.js')))execFileSync(process.execPath,['--check',path.join(r,'games',f)],{stdio:'ignore'});
execFileSync(process.execPath,['--check',path.join(r,'app.js')],{stdio:'ignore'});
execFileSync(process.execPath,['--check',path.join(r,'server/server.js')],{stdio:'ignore'});
const g=JSON.parse(fs.readFileSync(path.join(r,'server/games.json'))),p=JSON.parse(fs.readFileSync(path.join(r,'server/pets.json'))),features=(fs.readFileSync(path.join(r,'FEATURES_1000.md'),'utf8').match(/^\d+\. /gm)||[]).length;
if(g.length!==75)throw Error('game count');if(p.length!==100)throw Error('pet count');if(features!==1000)throw Error('feature count');
for(const id of g.map(x=>x.id))if(g.filter(x=>x.id===id).length>1)throw Error('duplicate game '+id);
const s=fs.readFileSync(path.join(r,'server/server.js'),'utf8');for(const x of ['/api/play','/api/rankings','/start','/ownerhelp','/taogiftcode','/taoevent','/taopet','/petsid','/baotri','/ban','/unban'])if(!s.includes(x))throw Error('missing '+x);
if(s.includes('/api/play')&&!s.includes("Math.floor(.42*n)"))throw Error('win gate');
console.log('PASS');
