const express=require('express');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const app=express();
app.disable('x-powered-by');
app.use(express.json({limit:'128kb'}));
const ROOT=path.join(__dirname,'..');
const DB_PATH=path.join(__dirname,'database','db.json');
const PORT=Number(process.env.PORT||10000);
const BOT_TOKEN=String(process.env.BOT_TOKEN||'');
const WEB_APP_URL=String(process.env.WEB_APP_URL||process.env.PUBLIC_URL||'').replace(/\/$/,'');
const PUBLIC_URL=String(process.env.PUBLIC_URL||WEB_APP_URL).replace(/\/$/,'');
const ADMIN_ID=String(process.env.ADMIN_ID||'');
let db={players:{},history:[],chat:[],giftcodes:{},pets:{},blocked:{},noticeLog:[]};
try{Object.assign(db,JSON.parse(fs.readFileSync(DB_PATH,'utf8')))}catch{}
for(const [k,empty] of Object.entries({players:{},history:[],chat:[],giftcodes:{},pets:{},blocked:{},noticeLog:[]}))if(!db[k])db[k]=empty;
let saveTimer=null;const clients=new Set(),seen=new Map();
function save(){if(saveTimer)return;saveTimer=setTimeout(()=>{saveTimer=null;const tmp=DB_PATH+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db),'utf8');fs.renameSync(tmp,DB_PATH)},90)}
function broadcast(event,payload){const msg=`event: ${event}\ndata: ${JSON.stringify(payload)}\n\n`;for(const res of clients){try{res.write(msg)}catch{clients.delete(res)}}}
function day(){return new Date().toISOString().slice(0,10)} function month(){return new Date().toISOString().slice(0,7)}
function tgVerify(initData){if(!BOT_TOKEN||!initData)return false;try{const p=new URLSearchParams(initData);const hash=p.get('hash');if(!hash)return false;p.delete('hash');const data=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n');const key=crypto.createHmac('sha256','WebAppData').update(BOT_TOKEN).digest();const exp=crypto.createHmac('sha256',key).update(data).digest('hex');return exp.length===hash.length&&crypto.timingSafeEqual(Buffer.from(exp),Buffer.from(hash))}catch{return false}}
function readUser(req,{required=true}={}){const init=req.body?.initData||req.headers['x-telegram-init-data']||'';if(BOT_TOKEN){if(!tgVerify(init)){if(required)throw Error('Phiên Telegram không hợp lệ. Hãy đóng và mở lại Mini App từ bot.');return req.body?.telegramUser||null}try{return JSON.parse(new URLSearchParams(init).get('user')||'{}')}catch{throw Error('Dữ liệu Telegram không hợp lệ')}}const u=req.body?.telegramUser;if(u?.id)return u;const q=req.query;if(q.id)return {id:q.id,first_name:q.first_name,username:q.username,photo_url:q.photo_url};throw Error('Thiếu Telegram ID')}
function authPlayer(req){const u=readUser(req);if(db.blocked[String(u.id)])throw Error('Tài khoản đang bị khóa.');return ensure(u)}
function reward(streak){if(streak>=26)return {xu:100000,spins:50,item:'nhan-doi-tien-thuong'};if(streak>=16)return {xu:10000,spins:5,item:'goi-qua-gia-tri'};if(streak>=6)return {xu:1000,spins:2,item:'the-vip-nhe'};return {xu:100*streak,spins:streak>=3?1:0,item:null}}
function ensure(u){const id=String(u.id);let p=db.players[id];if(!p){p={id,name:String(u.first_name||'Người chơi').slice(0,60),username:String(u.username||'').slice(0,60),photo_url:String(u.photo_url||''),balance:100000,level:1,xp:0,vip:0,vipPoints:0,currentStreak:0,bestStreak:0,lastLogin:null,loginMonth:null,weeklyWins:0,totalPlays:0,totalWins:0,totalWinXu:0,totalLossXu:0,freeSpins:0,inventory:{},pets:{},gameStats:{},friends:0,createdAt:Date.now()};db.players[id]=p;save()}
if(p.lastLogin!==day()){const last=p.lastLogin?new Date(p.lastLogin+'T00:00:00Z'):null;const now=new Date(day()+'T00:00:00Z');const gap=last?Math.round((now-last)/86400000):999;if(p.loginMonth!==month())p.currentStreak=0;p.currentStreak=gap===1?p.currentStreak+1:1;p.loginMonth=month();p.lastLogin=day();p.bestStreak=Math.max(p.bestStreak,p.currentStreak);const r=reward(p.currentStreak);p.balance+=r.xu;p.freeSpins+=r.spins;if(r.item)p.inventory[r.item]=(p.inventory[r.item]||0)+1;p._reward=r;save()}return p}
function safe(p){const q={...p};delete q._reward;return q}
// Stable game catalog loaded from one source of truth.
const defs=JSON.parse(fs.readFileSync(path.join(__dirname,'games.json'),'utf8'));
function maxBet(b){return Math.min(1000000,Math.floor(b*.2))}
function gameWin(p,g){const st=p.gameStats[g.id]||{plays:0,wins:0};const n=st.plays+1;return Math.floor(.4*n)>Math.floor(.4*(n-1))}
function symbol(seed,arr){return arr[Math.abs(seed)%arr.length]}
function makeDisplay(g,win){const seed=crypto.randomInt(0,1000000000);const mech=g.mechanic;let d={mechanic:mech,headline:g.name,values:[]};
if(mech==='dice'){const a=1+seed%6,b=1+Math.floor(seed/7)%6,c=1+Math.floor(seed/49)%6;d={...d,values:[a,b,c],sum:a+b+c}}
else if(mech==='reels'){const s=['🍒','🍋','🔔','💎','⭐','7️⃣','🐉'];let vals=[symbol(seed,s),symbol(Math.floor(seed/17),s),symbol(Math.floor(seed/97),s)];if(win)vals=[vals[0],vals[0],vals[0]];d.values=vals}
else if(mech==='wheel'||mech==='roulette'||mech==='baucua'){d.value=symbol(seed,['1','2','3','4','5','6','7','8','9','10','⭐','💎'])}
else if(mech==='coin'){d.value=seed%2?'MẶT NGỬA':'MẶT SẤP'}
else if(mech==='cards'||mech==='poker'||mech==='baccarat'){const ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'],suits=['♠','♥','♦','♣'];d.values=[0,1,2].map(i=>ranks[(seed>>i)%ranks.length]+suits[(seed>>((i+2)))%suits.length]);if(win)d.headline='Bộ bài thuận lợi'}
else if(mech==='keno'){d.values=[];for(let i=0;i<8;i++)d.values.push(1+((seed>>Math.min(i,20))+i*13)%45)}
else if(mech==='crash'){d.value=(1.2+(seed%500)/100).toFixed(2)+'x'}
else if(mech==='grid'||mech==='mines'){d.values=Array.from({length:25},(_,i)=>win&&i===seed%25?'💎':String(i+1))}
else {d.value=1+seed%99;d.values=[d.value]}
return d}
app.get('/health',(req,res)=>res.json({ok:true,service:'casino-slot-vietnam-v3',time:Date.now()}));
app.get('/api/bootstrap',(req,res)=>{try{const p=ensure(readUser(req,{required:false}));const reward=p._reward||null;delete p._reward;res.json({player:safe(p),loginReward:reward,gameCount:defs.length})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/play',(req,res)=>{try{if(maintenance)throw Error('Hệ thống đang bảo trì.');const p=authPlayer(req);const g=defs.find(x=>x.id===String(req.body.gameId||''));if(!g)throw Error('Game không tồn tại');const bet=Math.floor(Number(req.body.bet));const max=maxBet(p.balance);if(!Number.isSafeInteger(bet)||bet<100||bet>max)throw Error(`Cược hợp lệ: 100–${max.toLocaleString('vi-VN')} Xu`);if(p.balance<bet)throw Error('Không đủ Xu');const rid=String(req.body.requestId||'');if(rid&&seen.has(rid))return res.status(409).json({error:'Lượt chơi đã được xử lý'});if(rid)seen.set(rid,Date.now());for(const [k,t] of seen)if(Date.now()-t>120000)seen.delete(k);const win=gameWin(p,g),mult=win?(1.15+crypto.randomInt(0,486)/100):0;const result={win,multiplier:Number(mult.toFixed(2)),display:makeDisplay(g,win),durationMs:20000+crypto.randomInt(0,25001)};p.balance-=bet;p.totalPlays++;p.vipPoints+=Math.max(1,Math.floor(bet/100));p.xp+=10+Math.floor(bet/1000);const gs=p.gameStats[g.id]||{plays:0,wins:0};gs.plays++;if(win)gs.wins++;p.gameStats[g.id]=gs;if(win){const profit=Math.floor(bet*result.multiplier);p.balance+=bet+profit;p.totalWins++;p.totalWinXu+=profit;p.weeklyWins++;if(result.multiplier>=3)broadcast('big_win',{name:p.name,game:g.name,profit})}else p.totalLossXu+=bet;while(p.xp>=1000){p.xp-=1000;p.level++;p.balance+=Math.min(50000,p.level*500)}p.vip=Math.min(20,Math.floor(p.vipPoints/1000));db.history.unshift({id:crypto.randomUUID(),userId:p.id,gameId:g.id,gameName:g.name,bet,result:win?'win':'lose',multiplier:result.multiplier,time:Date.now()});db.history=db.history.slice(0,12000);save();broadcast('player_update',{id:p.id,balance:p.balance,level:p.level});res.json({player:safe(p),result})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/free-spin',(req,res)=>{try{const p=authPlayer(req),now=Date.now(),wait=6*60*60*1000; if(p.lastFreeSpinAt&&now-p.lastFreeSpinAt<wait) throw Error(`Free Spin còn ${Math.ceil((wait-(now-p.lastFreeSpinAt))/3600000)} giờ.`); const reward=500+crypto.randomInt(0,4501);p.balance+=reward;p.lastFreeSpinAt=now;p.freeSpins=Math.max(0,p.freeSpins-1);save();broadcast('system_notice',{text:`🎡 ${p.name} vừa nhận Free Spin.`});res.json({ok:true,reward,player:safe(p)})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/history',(req,res)=>res.json(db.history.filter(x=>String(x.userId)===String(req.query.id||'')).slice(0,80)));
app.get('/api/rankings',(req,res)=>{const ps=Object.values(db.players);res.json({richest:[...ps].sort((a,b)=>b.balance-a.balance).slice(0,100).map((p,i)=>({rank:i+1,name:p.name,balance:p.balance})),streak:[...ps].sort((a,b)=>b.bestStreak-a.bestStreak).slice(0,100).map((p,i)=>({rank:i+1,name:p.name,streak:p.bestStreak})),weekly:[...ps].sort((a,b)=>b.weeklyWins-a.weeklyWins).slice(0,100).map((p,i)=>({rank:i+1,name:p.name,wins:p.weeklyWins}))})});
app.get('/api/events',(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache, no-transform');res.setHeader('Connection','keep-alive');res.write(`event: ping\ndata: ${Date.now()}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res))});
app.get('/api/chat/stream',(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache, no-transform');res.setHeader('Connection','keep-alive');res.write(`event: chat_history\ndata: ${JSON.stringify(db.chat.slice(-60))}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res))});
app.post('/api/chat',(req,res)=>{try{const u=readUser(req);const text=String(req.body.text||'').trim();if(!text||text.length>300)throw Error('Tin nhắn không hợp lệ');const msg={id:crypto.randomUUID(),userId:String(u.id),name:u.first_name||'Người chơi',text,time:Date.now()};db.chat.push(msg);db.chat=db.chat.slice(-1000);save();broadcast('chat_message',msg);res.json(msg)}catch(e){res.status(400).json({error:e.message})}});

const SHOP={double_xp:{name:'Thẻ Nhân Đôi XP',price:5000},lucky_ticket:{name:'Vé May Mắn',price:2500},pet_food:{name:'Thức Ăn Pet',price:1200}};
app.get('/api/shop',(req,res)=>res.json(SHOP));
app.post('/api/shop/buy',(req,res)=>{try{const p=authPlayer(req),id=String(req.body.item||''),item=SHOP[id];if(!item)throw Error('Vật phẩm không tồn tại.');if(p.balance<item.price)throw Error('Không đủ Xu.');p.balance-=item.price;p.inventory[id]=(p.inventory[id]||0)+1;save();res.json({ok:true,player:safe(p),item})}catch(e){res.status(400).json({error:e.message})}});
function isAdmin(id){return ADMIN_ID&&String(id)===ADMIN_ID}
function adminUser(req){const u=readUser(req);if(!isAdmin(u.id))throw Error('Không có quyền ADMIN.');return u}
async function tg(method,body){if(!BOT_TOKEN)return null;const r=await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return r.json()}
function botButtons(){return {inline_keyboard:[[{text:'🎰 MỞ CASINO',web_app:{url:WEB_APP_URL}}],[{text:'🎁 Giftcode',callback_data:'gift_help'}]]}}
function webhookResponse(text,chatId,markup){return {method:'sendMessage',chat_id:chatId,text,reply_markup:markup||botButtons()}}
function ownerHelp(){return `🛡️ LỆNH ADMIN\n\n/thongbao <nội dung> — gửi thông báo tới toàn bộ người dùng.\n/taogiftcode <CODE> <XU> [PET_ID] — tạo giftcode; tùy chọn pet. Không công khai số tiền.\n/gift <ID> <XU|pet:ID> — tặng Xu hoặc pet cho Telegram ID.\n/setxu <ID> <XU> — đặt số dư.\n/setvip <ID> <0-20> — đặt VIP.\n/setlevel <ID> <level> — đặt cấp.\n/addpet <ID> <PET_ID> [số lượng] — thêm pet.\n/removepet <ID> <PET_ID> [số lượng] — xóa pet.\n/block <ID> — khóa tài khoản.\n/unblock <ID> — mở khóa tài khoản.\n/resetstreak <ID> — reset chuỗi đăng nhập.\n/stats — thống kê server.\n/maintenance <on|off> — bật/tắt bảo trì.\n/ownerhelp — hiển thị tài liệu lệnh này chỉ cho ADMIN.`}
let maintenance=false;
async function botUpdate(update){const m=update.message;if(!m)return null;const chatId=m.chat?.id,text=String(m.text||'').trim(),from=String(m.from?.id||'');if(text.startsWith('/start'))return webhookResponse(`🎰 CASINO SLOT VIETNAM\n\nChào mừng ${m.from?.first_name||'bạn'}! Nhấn nút dưới để mở Mini App.\n\nXu ảo, chơi giải trí, không nạp/rút tiền thật.`,chatId,botButtons());
if(text==='/ownerhelp'){if(isAdmin(from))return webhookResponse(ownerHelp(),chatId,{remove_keyboard:true});return webhookResponse('Lệnh không khả dụng.',chatId)}
if(!isAdmin(from))return null;
const parts=text.split(/\s+/),cmd=parts[0].toLowerCase();
if(cmd==='/thongbao'){const msg=text.slice(cmd.length).trim();if(!msg)return webhookResponse('Dùng: /thongbao nội dung',chatId);for(const id of Object.keys(db.players))tg('sendMessage',{chat_id:id,text:`📢 THÔNG BÁO\n\n${msg}`}).catch(()=>{});db.noticeLog.push({admin:from,text:msg,time:Date.now()});save();return webhookResponse(`✅ Đã phát thông báo tới ${Object.keys(db.players).length} người dùng.`,chatId)}
if(cmd==='/taogiftcode'){const code=(parts[1]||'').toUpperCase().replace(/[^A-Z0-9_-]/g,'');const amount=Number(parts[2]);const pet=parts[3]?String(parts[3]):null;if(!code||!Number.isSafeInteger(amount)||amount<1)return webhookResponse('Dùng: /taogiftcode CODE XU [PET_ID]',chatId);if(db.giftcodes[code])return webhookResponse('Code đã tồn tại.',chatId);db.giftcodes[code]={code,xu:amount,pet:pet,usedBy:null,createdAt:Date.now(),createdBy:from};save();for(const id of Object.keys(db.players))tg('sendMessage',{chat_id:id,text:`🎁 GIFTCode mới: ${code}\n\nNhập code trong game để nhận quà!`}).catch(()=>{});return webhookResponse(`✅ Tạo giftcode ${code}. Đã thông báo mọi người.`,chatId)}
if(cmd==='/gift'){const id=String(parts[1]||''),thing=String(parts[2]||'');const p=db.players[id];if(!p)return webhookResponse('Không tìm thấy ID.',chatId);if(thing.startsWith('pet:')){const pet=thing.slice(4);p.pets[pet]=(p.pets[pet]||0)+1;save();tg('sendMessage',{chat_id:id,text:`🐾 Bạn vừa nhận pet: ${pet}`}).catch(()=>{});return webhookResponse('✅ Đã tặng pet.',chatId)}const amount=Number(thing);if(!Number.isSafeInteger(amount)||amount<=0)return webhookResponse('Dùng /gift ID XU hoặc /gift ID pet:PET_ID',chatId);p.balance+=amount;save();tg('sendMessage',{chat_id:id,text:`🎁 Bạn vừa nhận ${amount.toLocaleString('vi-VN')} Xu từ ADMIN.`}).catch(()=>{});return webhookResponse('✅ Đã tặng Xu.',chatId)}
if(cmd==='/setxu'){const p=db.players[String(parts[1]||'')];const n=Number(parts[2]);if(!p||!Number.isSafeInteger(n)||n<0)return webhookResponse('Dùng: /setxu ID XU',chatId);p.balance=n;save();return webhookResponse('✅ Đã đặt số dư.',chatId)}
if(cmd==='/setvip'){const p=db.players[String(parts[1]||'')];const n=Number(parts[2]);if(!p||!Number.isInteger(n)||n<0||n>20)return webhookResponse('Dùng: /setvip ID 0-20',chatId);p.vip=n;save();return webhookResponse('✅ Đã đặt VIP.',chatId)}
if(cmd==='/setlevel'){const p=db.players[String(parts[1]||'')];const n=Number(parts[2]);if(!p||!Number.isInteger(n)||n<1)return webhookResponse('Dùng: /setlevel ID level',chatId);p.level=n;save();return webhookResponse('✅ Đã đặt level.',chatId)}
if(cmd==='/addpet'||cmd==='/removepet'){const p=db.players[String(parts[1]||'')],pet=String(parts[2]||''),n=Math.max(1,Number(parts[3]||1));if(!p||!pet||!Number.isSafeInteger(n))return webhookResponse(`Dùng: ${cmd} ID PET_ID [số lượng]`,chatId);p.pets[pet]=(p.pets[pet]||0)+(cmd==='/addpet'?n:-n);if(p.pets[pet]<=0)delete p.pets[pet];save();return webhookResponse('✅ Đã cập nhật pet.',chatId)}
if(cmd==='/block'||cmd==='/unblock'){const id=String(parts[1]||'');if(!db.players[id])return webhookResponse('Không tìm thấy ID.',chatId);if(cmd==='/block')db.blocked[id]={at:Date.now(),by:from};else delete db.blocked[id];save();return webhookResponse('✅ Đã cập nhật trạng thái tài khoản.',chatId)}
if(cmd==='/resetstreak'){const p=db.players[String(parts[1]||'')];if(!p)return webhookResponse('Không tìm thấy ID.',chatId);p.currentStreak=0;save();return webhookResponse('✅ Đã reset streak.',chatId)}
if(cmd==='/stats'){const ps=Object.values(db.players);const total=ps.reduce((a,p)=>a+p.totalPlays,0),wins=ps.reduce((a,p)=>a+p.totalWins,0),xu=ps.reduce((a,p)=>a+p.balance,0);return webhookResponse(`📊 SERVER\nNgười chơi: ${ps.length}\nTổng ván: ${total}\nTổng thắng: ${wins}\nTổng Xu đang lưu: ${xu.toLocaleString('vi-VN')}\nGiftcode: ${Object.keys(db.giftcodes).length}\nChat: ${db.chat.length}`,chatId)}
if(cmd==='/maintenance'){const v=(parts[1]||'').toLowerCase();if(v!=='on'&&v!=='off')return webhookResponse('Dùng: /maintenance on|off',chatId);maintenance=v==='on';return webhookResponse(`✅ Bảo trì: ${maintenance?'BẬT':'TẮT'}.`,chatId)}
return webhookResponse('Lệnh ADMIN không hợp lệ. Dùng /ownerhelp.',chatId)}
app.post('/telegram/webhook',(req,res)=>{try{const resp=botUpdate(req.body);if(resp)res.status(200).json(resp);else if(req.body?.callback_query?.data==='gift_help'){res.status(200).json({method:'answerCallbackQuery',callback_query_id:req.body.callback_query.id,text:'Vào Mini App → Nhiệm vụ để nhập giftcode.'})}else res.sendStatus(200)}catch(e){console.error('Webhook:',e.message);res.sendStatus(200)}});
app.post('/api/giftcode/redeem',(req,res)=>{try{const p=authPlayer(req),code=String(req.body.code||'').trim().toUpperCase(),g=db.giftcodes[code];if(!g)throw Error('Giftcode không tồn tại.');if(g.usedBy)throw Error('Giftcode đã được sử dụng.');p.balance+=g.xu;if(g.pet)p.pets[g.pet]=(p.pets[g.pet]||0)+1;g.usedBy=p.id;g.usedAt=Date.now();save();broadcast('system_notice',{text:`🎁 ${p.name} vừa đổi giftcode thành công.`});res.json({ok:true,player:safe(p),pet:g.pet||null})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/admin/set-webhook',async(req,res)=>{try{const u=adminUser(req);const base=String(req.body.url||PUBLIC_URL).replace(/\/$/,'');if(!base)throw Error('Thiếu URL');const out=await tg('setWebhook',{url:base+'/telegram/webhook',allowed_updates:['message']});res.json(out)}catch(e){res.status(403).json({error:e.message})}});
app.use(express.static(ROOT));
(async()=>{if(BOT_TOKEN&&PUBLIC_URL){try{const r=await tg('setWebhook',{url:PUBLIC_URL+'/telegram/webhook',allowed_updates:['message']});console.log('Telegram webhook',r?.ok?'OK':'FAILED')}catch(e){console.error('Webhook setup',e.message)}}})();
app.listen(PORT,'0.0.0.0',()=>console.log(`CASINO SLOT VIETNAM V3 on ${PORT}`));
